<center>

![](https://drive.google.com/uc?export=view&id=1R6EAVE0Ysym-UNtZR-Ze_HcqQLDmH0bd) 
<p> 
College: Engineering and Information Technology <br>
Department: Information Technology <br>
Program: Data Analytics <br>
Academic semester: Fall 2021- 2022 <br>
Programming for Data Analytics I Lab DAT205 <br>
<br>
</p></center>
Array
</p></center>

In [ ]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################


# 7.7 `array` Operators

### Arithmetic Operations with `array`s and Individual Numeric Values

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [6]:
numbers  # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [7]:
numbers += 10

In [8]:
numbers

array([11, 12, 13, 14, 15])

### Broadcasting 

### Arithmetic Operations Between `array`s 

In [9]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [10]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [11]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

### Comparing arrays

In [12]:
numbers

array([11, 12, 13, 14, 15])

In [13]:
numbers >= 13

array([False, False,  True,  True,  True])

In [14]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [15]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [16]:
numbers == numbers2

array([False, False, False, False, False])

In [17]:
numbers == numbers

array([ True,  True,  True,  True,  True])

# 7.8 NumPy Calculation Methods

In [18]:
import numpy as np

In [19]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [20]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [24]:
grades.sum()

1054

In [25]:
grades.min()

70

In [26]:
grades.max()

100

In [27]:
grades.mean()

87.83333333333333

In [31]:
grades.std()

8.792357792739987

In [32]:
grades.var()

77.30555555555556

### Calculations by Row or Column

In [33]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [34]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

# 7.9 Universal Functions

In [35]:
import numpy as np

In [36]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [37]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [38]:
numbers2 = np.arange(1, 7) * 10

In [39]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [40]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

### Broadcasting with Universal Functions

In [41]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [42]:
numbers3 = numbers2.reshape(2, 3)

In [43]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
numbers4 = np.array([2, 4, 6])

In [45]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

# 7.10 Indexing and Slicing 

### Indexing with Two-Dimensional `array`s

In [46]:
import numpy as np

In [47]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [48]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [49]:
grades[0, 1]  # row 0, column 1

96

### Selecting a Subset of a Two-Dimensional `array`’s Rows

In [50]:
grades[1]

array([100,  87,  90])

In [51]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [52]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

### Selecting a Subset of a Two-Dimensional `array`’s Columns

In [53]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [54]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [55]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

# 7.11 Views: Shallow Copies

In [56]:
import numpy as np

In [57]:
numbers = np.arange(1, 6)

In [58]:
numbers

array([1, 2, 3, 4, 5])

In [59]:
numbers2 = numbers.view()

In [60]:
numbers2

array([1, 2, 3, 4, 5])

In [61]:
id(numbers)

139636952616560

In [62]:
id(numbers2)

139636971782864

In [63]:
numbers[1] *= 10

In [64]:
numbers2

array([ 1, 20,  3,  4,  5])

In [65]:
numbers

array([ 1, 20,  3,  4,  5])

In [66]:
numbers2[1] /= 10

In [67]:
numbers

array([1, 2, 3, 4, 5])

In [68]:
numbers2

array([1, 2, 3, 4, 5])

### Slice Views

In [69]:
numbers2 = numbers[0:3]

In [70]:
numbers2

array([1, 2, 3])

In [71]:
id(numbers)

139636952616560

In [72]:
id(numbers2)

139636952131504

In [75]:
numbers[1] *= 20

In [76]:
numbers

array([ 1, 40,  3,  4,  5])

In [77]:
numbers2

array([ 1, 40,  3])

# 7.12 Deep Copies

In [78]:
import numpy as np

In [79]:
numbers = np.arange(1, 6)

In [80]:
numbers

array([1, 2, 3, 4, 5])

In [81]:
numbers2 = numbers.copy()

In [82]:
numbers2

array([1, 2, 3, 4, 5])

In [83]:
numbers[1] *= 10

In [84]:
numbers

array([ 1, 20,  3,  4,  5])

In [85]:
numbers2

array([1, 2, 3, 4, 5])

# 7.13 Reshaping and Transposing 

### `reshape` vs. `resize` 

The difference between reshape() and resize() is that reshape() does not change the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array. 

In [86]:
import numpy as np

In [87]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [88]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [89]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [90]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [91]:
grades.resize(1, 6)

In [92]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

### `flatten` vs. `ravel` 

In [93]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [94]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [95]:
flattened = grades.flatten()

In [96]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [97]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [98]:
flattened[0] = 100

In [99]:
flattened

array([100,  96,  70, 100,  87,  90])

In [100]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [101]:
raveled = grades.ravel()

In [102]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [103]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [104]:
raveled[0] = 100

In [105]:
raveled

array([100,  96,  70, 100,  87,  90])

In [106]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Transposing Rows and Columns

In [107]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [108]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Horizontal and Vertical Stacking

In [109]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [110]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [111]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])