<center>

![](https://drive.google.com/uc?export=view&id=1R6EAVE0Ysym-UNtZR-Ze_HcqQLDmH0bd) 
<p> 
College: Engineering and Information Technology <br>
Department: Information Technology <br>
Program: Data Analytics <br>
Academic semester: Fall 2021- 2022 <br>
Programming for Data Analytics I Lab DAT205 <br>
<br>
</p></center>
Array
</p></center>

In [ ]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################


# 7.2 Creating `arrays` from Existing Data 

In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

### Multidimensional Arguments

In [8]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])


# 7.2 Self Check

**2. _(IPython Session)_** Create a one-dimensional `array` from a list comprehension that produces the even integers from 2 through 20. 

**Answer:** 

In [9]:
import numpy as np

np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**3. _(IPython Session)_** Create a 2-by-5 `array` containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row. 

**Answer:** 

In [10]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

# 7.3 `array` Attributes 

In [32]:
import numpy as np

In [33]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [34]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [36]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

### Determining an `array`’s Element Type

In [37]:
integers.dtype

dtype('int64')

In [38]:
floats.dtype

dtype('float64')

### Determining an `array`’s Dimensions

In [39]:
integers.ndim

2

In [40]:
floats.ndim

1

In [41]:
integers.shape

(2, 3)

In [42]:
floats.shape

(5,)

### Determining an `array`’s Number of Elements and Element Size

In [43]:
integers.size

6

In [ ]:
# Length of one array element in bytes.
integers.itemsize

8

In [45]:
floats.size

5

In [46]:
floats.itemsize

8

In [47]:
test = np.array([[1, 2, 3], [4, 5, 6]],dtype=np.complex128)
test.itemsize

16

### Iterating through a Multidimensional `array`’s Elements

In [48]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print() 

1  2  3  
4  5  6  


In [ ]:
for i in integers.flat:
    print(i, end='  ')

1  2  3  4  5  6  

# 7.4 Filling `array`s with Specific Values

In [50]:
import numpy as np

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [53]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

# 7.5 Creating `array`s from Ranges 

### Creating Integer Ranges with `arange`

In [54]:
import numpy as np

In [55]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [56]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [57]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

### Creating Floating-Point Ranges with `linspace` 

In [58]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshaping an `array` 

In [59]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Displaying Large `array`s 

In [63]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [64]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

**2. _(IPython Session)_** Use NumPy function `arange` to create an `array` of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 `array`.

**Answer:** 

In [65]:
import numpy as np

In [66]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

# 7.6 List vs. `array` Performance: Introducing `%timeit` 

### Timing the Creation of a List Containing Results of 6,000,000 Die Rolls 

In [67]:
import random

In [68]:
%timeit rolls_list = \
   [random.randrange(1, 7) for i in range(0, 6_000_000)]

1 loop, best of 5: 7.25 s per loop


### Timing the Creation of an `array` Containing Results of 6,000,000 Die Rolls  

In [69]:
import numpy as np

In [70]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

10 loops, best of 5: 69.9 ms per loop


### 60,000,000 and 600,000,000 Die Rolls  

In [71]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

1 loop, best of 5: 667 ms per loop


In [72]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

1 loop, best of 5: 6.55 s per loop


### Customizing the %timeit Iterations  

Documentation: https://ipython.org/ipython-doc/dev/interactive/magics.html#magic-timeit


In [73]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

3 loops, best of 2: 68.9 ms per loop



# 7.6 Self Check

**1. _(IPython Session)_** Use `%timeit` to compare the execution time of the following two statements. The first uses a list comprehension to create a list of the integers from 0 to 9,999,999 then totals them with the built-in `sum` function. The second statement does the same thing using an `array` and its `sum` method.
```python
sum([x for x in range(10_000_000)])
np.arange(10_000_000).sum()
```

**Answer:** 

In [74]:
import numpy as np

In [75]:
%timeit sum([x for x in range(10_000_000)])

1 loop, best of 5: 853 ms per loop


In [76]:
%timeit np.arange(10_000_000).sum()

10 loops, best of 5: 27.7 ms per loop


The statement with the list comprehension took 26 times longer to execute than the one with the `array`. 